classDiagram
  class A {
    x : P
  }
  class B {
    x : P
  }
  class C {
    x : P
  }
  class D {
    x : P
  }
  class E {
    x : P
  }
  class P {
  }
  P "1" --* A : x
  P "1" --* C : x
  P "1" --* D : x
  P "1" --* E : x
  P "1" --o B : x
